#!/bin/bash

if [ $# -eq 1 ]
then
   echo "rm -r dev/dev$1/data/bitcask"
   rm -r dev/dev$1/data/bitcask
elif [ $# -eq 2 ]
then
   for i in $(seq $1 $2)
   do
      echo "rm -r dev/dev$i/data/bitcask"
      rm -r dev/dev$i/data/bitcask
   done
else
   echo "USAGE: $0 dev_NUM"
   echo "       $0 starting_NUM ending_NUM"
   exit -1
fi
