#!/bin/bash

if [ $# -eq 2 ]
then
   echo "./dev/dev$2/bin/ziryab-admin join ziryab$1@127.0.0.1"
   ./dev/dev$2/bin/ziryab-admin join ziryab$1@127.0.0.1
elif [ $# -eq 3 ]
then
   for i in $(seq $2 $3)
   do
      echo "./dev/dev$i/bin/ziryab-admin join ziryab$1@127.0.0.1"
      ./dev/dev$i/bin/ziryab-admin join ziryab$1@127.0.0.1
   done
else
   echo "USAGE: $0 <node to join> <joining node>"
   echo "       $0 <node to join> <joining range start> <joining range end>"
   exit -1
fi
