#!/bin/bash

if [ $# -eq 1 ]
then
   echo "./dev/dev$1/bin/ziryab-admin console-state"
   ./dev/dev$1/bin/ziryab-admin console-state
elif [ $# -eq 2 ]
then
   for i in $(seq $1 $2)
   do
      echo "./dev/dev$i/bin/ziryab-admin console-state"
      ./dev/dev$i/bin/ziryab-admin console-state
   done
else
   echo "USAGE: $0 dev_NUM"
   echo "       $0 starting_NUM ending_NUM"
   exit -1
fi
